#!/usr/bin/env python3
"""One-command interactive setup — run this first.

Asks for everything in the terminal, then logs in BOTH connections:

  * userbot (your account)  -> asks phone number, then the OTP code Telegram
                               sends you, and your 2FA password if you have one.
  * bot (from @BotFather)   -> logs in from the token, no code needed.

It writes .env, auto-detects your OWNER_ID from the userbot login, and creates
the session files so the other scripts just work.

Run:  python setup.py
"""
from __future__ import annotations

import asyncio
from getpass import getpass
from pathlib import Path

from telethon import TelegramClient

BASE = Path(__file__).resolve().parent
ENV_PATH = BASE / ".env"
USERBOT_SESSION = str(BASE / "userbot")
BOT_SESSION = str(BASE / "bot")


def ask(prompt: str, default: str | None = None, secret: bool = False) -> str:
    label = f"{prompt}"
    if default:
        label += f" [{default}]"
    label += ": "
    while True:
        value = (getpass(label) if secret else input(label)).strip()
        if not value and default is not None:
            return default
        if value:
            return value
        print("  (required)")


def write_env(values: dict[str, str]) -> None:
    lines = ["# Generated by setup.py — do not commit this file.\n"]
    for key, val in values.items():
        # Keep newlines in DM_MESSAGE literal so dotenv reads them back cleanly.
        safe = val.replace("\n", "\\n")
        lines.append(f"{key}={safe}\n")
    ENV_PATH.write_text("".join(lines))
    print(f"\nWrote {ENV_PATH}")


async def main() -> None:
    print("=" * 60)
    print(" Channel Migration Bot — setup")
    print(" Get API_ID / API_HASH from https://my.telegram.org")
    print(" Get the bot token from @BotFather")
    print("=" * 60)

    api_id = ask("API_ID")
    api_hash = ask("API_HASH", secret=True)
    bot_token = ask("BOT_TOKEN", secret=True)
    source_channel = ask("SOURCE_CHANNEL (@username or -100... id)")
    new_channel_link = ask("NEW_CHANNEL_LINK (invite link to your new channel)")
    dm_message = ask(
        "DM_MESSAGE (use {name} and {link})",
        default="Hey {name}! We've moved — join our new channel: {link}",
    )

    print("\nRate limiting (press Enter to accept defaults):")
    dm_delay = ask("DM_DELAY_SECONDS", default="4")
    batch_size = ask("BATCH_SIZE", default="25")
    batch_pause = ask("BATCH_PAUSE_SECONDS", default="60")

    # --- Log in the userbot (this triggers the OTP prompt) -----------------
    print("\n" + "-" * 60)
    print(" Logging in your USERBOT account.")
    print(" Telegram will send a login code to your app; enter it below.")
    print("-" * 60)
    phone = ask("Phone number (with country code, e.g. +15551234567)")

    userbot = TelegramClient(USERBOT_SESSION, int(api_id), api_hash)
    # Telethon prompts for the OTP code and (if set) the 2FA password itself.
    await userbot.start(phone=lambda: phone)
    me = await userbot.get_me()
    detected_owner = str(me.id)
    print(f"Userbot logged in as {me.first_name} (id {detected_owner}).")
    await userbot.disconnect()

    owner_id = ask("OWNER_ID (who can use /broadcast)", default=detected_owner)

    # --- Log in the bot from its token -------------------------------------
    print("\nLogging in the BOT from its token...")
    bot = TelegramClient(BOT_SESSION, int(api_id), api_hash)
    await bot.start(bot_token=bot_token)
    bot_me = await bot.get_me()
    print(f"Bot logged in as @{bot_me.username}.")
    await bot.disconnect()

    # --- Persist config ----------------------------------------------------
    write_env(
        {
            "API_ID": api_id,
            "API_HASH": api_hash,
            "BOT_TOKEN": bot_token,
            "OWNER_ID": owner_id,
            "SOURCE_CHANNEL": source_channel,
            "NEW_CHANNEL_LINK": new_channel_link,
            "DM_MESSAGE": dm_message,
            "DM_DELAY_SECONDS": dm_delay,
            "BATCH_SIZE": batch_size,
            "BATCH_PAUSE_SECONDS": batch_pause,
        }
    )

    print("\nAll set. Next steps:")
    print("  1) python fetch_pending.py   # userbot lists the join-request backlog")
    print("  2) python dm_backlog.py      # bot DMs them the invite")
    print("  3) python live_bot.py        # keep running: auto-DM new joiners + /broadcast")
    print("\nMake sure the BOT is an ADMIN of the source channel (with 'Add users'),")
    print("and that your own account is an admin there too.")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
